name: PlatformIO Build
on: [workflow_dispatch, push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO & update runner
      run: pip install --upgrade platformio

    - name: Compile firmware
      run: |
        pio run
        pio run --target buildfs

        for compiled_folder in .pio/build/*; do
            if [ -d "$compiled_folder" ]; then

              firmware_name=$(basename "$compiled_folder")

              mkdir ./updater/latest/${firmware_name} || true
              cp "$compiled_folder/firmware.bin" "./updater/latest/${firmware_name}/firmware.bin"
              cp "$compiled_folder/littlefs.bin" "./updater/latest/${firmware_name}/filesystem.bin"
            fi
        done

    - name: Commit files
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        rm -rf .pio/build/*
        cp ./src/versions.txt ./updater/versions.txt

        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git tag -d $GITHUB_REF_NAME
        git tag $GITHUB_REF_NAME
        git commit -a -m "🏗️ Firmware v$(head -n 1 ./updater/versions.txt)"
    
    - name: Push changes
      if: startsWith(github.ref, 'refs/tags/')
      uses: ad-m/github-push-action@master
      with:
        force: true
        tags: true
