name: PlatformIO Build
on: [workflow_dispatch, push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Compile firmware & Build filesystem
      run: |
        cp ./src/versions.txt ./updater/versions.txt

        rm -rf ./data/version.txt || true
        mkdir ./data || true
        head -n 1 ./updater/versions.txt >> ./data/version.txt
        
        pio run
        pio run --target buildfs

        for compiled_folder in .pio/build/*; do
            if [ -d "$compiled_folder" ]; then

              firmware_name=$(basename "$compiled_folder")

              mkdir ./updater/latest/${firmware_name} || true
              cp "$compiled_folder/firmware.bin" "./updater/latest/${firmware_name}/firmware.bin"
              cp "$compiled_folder/littlefs.bin" "./updater/latest/${firmware_name}/filesystem.bin"
            fi
        done

    - name: (?) Push files
      run: |

        if [ -n "$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} -- 'src/versions.txt')" ]; then
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "🏗️ Firmware v$(head -n 1 ./updater/versions.txt)"
          git push
        else
          echo "Version list not changed, aborting push."
        fi