name: PlatformIO Build
on: [workflow_dispatch, push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Check filesystem existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "data"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Compile firmware
      run: |
        pio run

        for compiled_folder in .pio/build/*; do
            if [ -d "$compiled_folder" ]; then

              firmware_name=$(basename "$compiled_folder")

              cp "$compiled_folder/firmware.bin" "./updater/latest/${firmware_name}/firmware.bin"
            fi
        done

    - name: Compile filesystem
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        pio run --target buildfs
        
        for compiled_folder in .pio/build/*; do
          if [ -d "$compiled_folder" ]; then

            firmware_name=$(basename "$compiled_folder")

            cp "$compiled_folder/*fs.bin" "./updater/latest/${firmware_name}/filesystem.bin"
          fi
        done

    - name: Push changes to repo
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        rm -rf .pio/build/*
        cp ./src/versions.txt ./updater/versions.txt

        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git pull
        git add .
        git commit -m "🏗️ Firmware v$(head -n 1 ./updater/versions.txt)"
        git push